### ISSUE TITLE
Pre-made Verified Templates for Gaming SDK Integration

### ISSUE THREAD

**Issue by serenaho** [ChainSafe/game-web3gl#23]
When minting an NFT on the marketplace, we're aiming for a Properties section that will have pre-made and verified templates including all the necessary information for integration with our Gaming SDK. The user should be able to define what fields they would like to use and input values as needed (i.e. all properties needed to create a 3D object usable in-game).

**Comment by leon-do** [comment]
should I closet his?

**Comment by serenaho** [comment]
Yes for now, thanks @leon-do  :)
