### ISSUE TITLE
Web3Wallet.Sha3() != web3.utils.soliditySha3()

### ISSUE THREAD

**Issue by TooSizzle** [ChainSafe/game-web3gl#32]
Like in the title, i want to know if the both function works exactly the same.
Cause, the web3.utils.soliditySha3 function can have multiple parameters, and the Web3Wallet.Sha3() not.

Do you have any documentation on how to use the Web3Wallet.Sha3() to get a same result as the web3.utils.soliditySha3 ?

Thx for you answer !

**Comment by KBryan** [comment]
Sorry for the late response on this. No, they do not. There has been a conflict with Nethereum. I'm currently doing updates this week.

**Comment by TooSizzle** [comment]
Better late than never ! Thanks ! It would be very nice if it work !!
